# Baseline Configuration for Battery Offloading Simulation
# This configuration represents a typical mobile device scenario with
# realistic battery, processing, and network parameters for research baseline

# Battery specifications for a typical smartphone
battery:
  capacity_mah: 5000           # 5000 mAh battery capacity
  capacity_wh: 18.5            # 18.5 Wh (3.7V nominal * 5Ah)
  initial_soc: 80.0            # Start at 80% charge (realistic scenario)
  discharge_rate_ma: 200       # Base discharge rate in mA

# Power consumption parameters for robot activities
power:
  active_local_mw: 2500.0      # 2.5W during local computation (intensive tasks)
  tx_mw: 800.0                 # 800mW during transmission
  rx_mw: 400.0                 # 400mW during reception  
  idle_mw: 150.0               # 150mW baseline idle power

# Local device processing capabilities
local_service:
  processing_rate_ops_per_sec: 1000000.0    # 1M operations per second
  power_consumption_mw: 2500.0              # 2.5W power consumption

# Edge server processing capabilities (realistic edge computing)
edge_service:
  processing_rate_ops_per_sec: 5000000.0    # 5M operations per second (5x faster)
  power_consumption_mw: 0.0                 # No local power consumption for edge

# Cloud server processing capabilities (powerful cloud resources)
cloud_service:
  processing_rate_ops_per_sec: 10000000.0   # 10M operations per second (10x faster)
  power_consumption_mw: 0.0                 # No local power consumption for cloud

# Network parameters for edge communication (5G/WiFi 6)
edge_network:
  latency_ms: 20.0             # 20ms latency to edge
  bandwidth_mbps: 100.0        # 100 Mbps bandwidth
  transmission_power_mw: 800.0 # 800mW transmission power

# Network parameters for cloud communication (Internet)
cloud_network:
  latency_ms: 100.0            # 100ms latency to cloud
  bandwidth_mbps: 50.0         # 50 Mbps bandwidth
  transmission_power_mw: 800.0 # 800mW transmission power

# Task generation parameters (balanced workload)
task_generation:
  arrival_rate_per_sec: 2.0    # 2 tasks per second (moderate load)
  avg_operations: 5000000.0    # Average 5M operations per task
  avg_data_size_mb: 1.0        # Average 1MB data per task
  nav_ratio: 0.2               # 20% NAV tasks (always local)
  slam_ratio: 0.1              # 10% SLAM tasks (always local)
  edge_affinity_ratio: 0.5     # 50% of generic tasks prefer edge (balanced)

# Simulation control parameters
simulation:
  duration_sec: 600.0          # 10 minute simulation
  soc_threshold: 30.0          # 30% SoC threshold for offloading decisions
  random_seed: 42              # Fixed seed for reproducible results
  output_directory: "results"  # Directory for output files