# Low Battery Test for Cloud Execution Analysis

battery:
  capacity_mah: 5000
  capacity_wh: 18.5
  initial_soc: 25.0            # Start below 30% to trigger cloud execution
  discharge_rate_ma: 200

power:
  active_local_mw: 3200.0
  tx_mw: 800.0
  rx_mw: 400.0
  idle_mw: 150.0

local_service:
  processing_rate_ops_per_sec: 6000000.0
  power_consumption_mw: 3200.0

edge_service:
  processing_rate_ops_per_sec: 8000000.0
  power_consumption_mw: 0.0

cloud_service:
  processing_rate_ops_per_sec: 15000000.0
  power_consumption_mw: 0.0

edge_network:
  latency_ms: 35.0
  bandwidth_mbps: 25.0
  transmission_power_mw: 800.0
  bw_up_mbps: 15.0
  bw_down_mbps: 50.0
  rtt_ms: 35.0
  jitter_ms: 5.0

cloud_network:
  latency_ms: 120.0
  bandwidth_mbps: 30.0
  transmission_power_mw: 1000.0
  bw_up_mbps: 20.0
  bw_down_mbps: 60.0
  rtt_ms: 120.0
  jitter_ms: 15.0

# Maximize generic tasks to test cloud execution
task_generation:
  arrival_rate_per_sec: 2.0
  avg_operations: 5000000.0
  avg_data_size_mb: 2.0
  nav_ratio: 0.05              # Minimal NAV tasks
  slam_ratio: 0.05             # Minimal SLAM tasks
  edge_affinity_ratio: 0.3     # Mix of edge/local affinity

simulation:
  duration_sec: 300.0
  soc_threshold: 30.0          # This matches the hard-coded threshold
  random_seed: 42
  output_directory: "results_low_battery"